### ISSUE TITLE
Error when convert tfrecords data to npz data

### ISSUE THREAD

**Issue by lqzhao** [SJingjia/PlaneRecTR#4]
Hi, thanks for the good work. When I downloaded tfrecords data from [PlaneNet](https://github.com/art-programmer/PlaneNet),  and then ran the commands to convert it to npz data and generate json files required by [detectron2](https://github.com/facebookresearch/detectron2),  I met the following error. How can I solve it? Thanks!

> 

...
...
18899
18999
19099
19199
19299
Traceback (most recent call last):
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[{{node batch}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "data_tools/convert_tfrecords.py", line 59, in <module>
    img, gt_dict = sess.run([img_inp_train, global_gt_dict_train])
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.OutOfRangeError: FIFOQueue '_2_batch/fifo_queue' is closed and has insufficient elements (requested 1, current size 0)
	 [[node batch (defined at /home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'batch':
  File "data_tools/convert_tfrecords.py", line 46, in <module>
    img_inp_train, global_gt_dict_train, local_gt_dict_train = reader_train.getBatch(filename_queue_train, batchSize=1, getLocal=True)
  File "/home/zlq/code/PlaneRecTR/PlanarReconstruction/data_tools/RecordReaderAll.py", line 62, in getBatch
    tf.train.batch([image, planes, depth, normal, semantics, segmentation, boundary, numPlanes, features['image_path'], features['info']], batch_size=batchSize, capacity=(NUM_THREADS + 2) * batchSize, num_threads=1)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/training/input.py", line 1020, in batch
    name=name)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/training/input.py", line 789, in _batch
    dequeued = queue.dequeue_many(batch_size, name=name)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/ops/data_flow_ops.py", line 489, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/ops/gen_data_flow_ops.py", line 3862, in queue_dequeue_many_v2
    timeout_ms=timeout_ms, name=name)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/home/zlq/anaconda3/envs/planerectr/lib/python3.7/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

> 
![image](https://github.com/SJingjia/PlaneRecTR/assets/43566465/635659c9-8f3b-49f1-89ba-8d12e80c8378)

**Comment by lqzhao** [comment]
Hi, would you mind sharing the file 'scannetv1_plane_len47693_train.json' directly? Thank you!

**Comment by SJingjia** [comment]
Hi, scannetv1 json files were uploaded to https://drive.google.com/drive/folders/1ldpL1vs1YPCi-OvyRmSA4D-nFAwCJV6E?usp=sharing

**Comment by lqzhao** [comment]
> Hi, scannetv1 json files were uploaded to https://drive.google.com/drive/folders/1ldpL1vs1YPCi-OvyRmSA4D-nFAwCJV6E?usp=sharing

Thanks. I only generated **18,467 training samples** and 760 validation samples. I believe the validation set matches your configuration. Could you please share **the entire 'scannetv1_plane' folder (as shown below)?** Because I am still unable to run the commands successfully.

![image](https://github.com/SJingjia/PlaneRecTR/assets/43566465/cbec4c3a-7f02-428c-a113-4d8d43e22265)

**Comment by SJingjia** [comment]
Sorry for the late reply. Due to the large size of the file, it took some time and effort to upload it. You can download it from [here](https://pan.baidu.com/s/1EY81LXQlbwNFHy6SlfK8Bg?pwd=psy9).

**Comment by lqzhao** [comment]
Thank you very much!

**Comment by zzh-whu-pixel** [comment]
Hello, thank you for previously sharing the full scannetv1_plane folder.
I am trying to reproduce PlaneRecTR for academic research, but the Baidu Pan
link in this issue has expired. The original PlaneNet TFRecord download links
are also unavailable now.
